name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Set up Android SDK and NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;23.1.7779620"
          echo "ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/23.1.7779620" >> $GITHUB_ENV

      - name: Grant Execute Permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Android App
        run: ./gradlew :app:assembleDebug --parallel --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4.6.1
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Build Logs (if build fails)
        if: failure()
        uses: actions/upload-artifact@v4.6.1
        with:
          name: build-logs
          path: app/build/reports/
